'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9164
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("peta.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property azki1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("azki1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property azkiBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("azkiBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property azkiLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("azkiLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_button_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-button-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hololive_Production_logo_svg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hololive_Production_logo.svg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property holomem_en1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("holomem-en1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property holomem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("holomem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property light_blue_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("light-blue-button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miko1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miko1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mikoBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mikoBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mikoLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mikoLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property roboco1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("roboco1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property robocoBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("robocoBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property robocoLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("robocoLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rounded_corner_button_white_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rounded-corner-button(white)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rushia1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rushia1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sora1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sora1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sora2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sora2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property soraBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soraBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property soraLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soraLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suisei1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suisei1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suiseiBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suiseiBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suiseiLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suiseiLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property talentHeader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("talentHeader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
